package com.example.data.model

/**
 * Strongly typed domain model representing a structured Brand Concept generated by AI
 * in Phase 2 (AI Brand Genius) from a Phase 1 SnapAnalysis.
 */
data class BrandConcept(
    val id: String,
    val ownerUid: String,
    val sourceSnapAnalysisId: String,
    val photoUri: String = "",
    val businessMode: String = "MERCH", // "MERCH" or "REAL_SHOP"
    val brandName: String,
    val usernameSuggestion: String,
    val tagline: String,
    val shortDescription: String = "",
    val brandStory: String,
    val targetAudience: String = "Global Audience",
    val brandPersonality: List<String> = emptyList(), // e.g. ["playful", "warm", "personal", "premium"]
    val brandKeywords: List<String> = emptyList(),
    val visualStyle: String = "Modern & Clean",
    val suggestedColorDirection: List<String> = listOf("#6750A4", "#E8DEF8", "#F97316"), // User's future brand palette (hex or color names)
    val typographyPersonality: String = "Modern Sans-serif",
    val logoConcept: String = "Minimalist Icon with Bold Wordmark", // Textual description of the logo concept (wordmark/icon)
    val productNamingStyle: String = "Creative & Descriptional",
    val marketingAngle: String = "Direct to Consumer",
    val customizationDirective: String? = null, // e.g. "more Ghanaian", "more luxury", "more minimalist"
    val createdAt: Long = System.currentTimeMillis(),
    val updatedAt: Long = System.currentTimeMillis()
)
